services:
  backend:
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: unless-stopped
    ports:
      - "34496:34496"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:34496
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:34496/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s